name: Selenium
on: [push]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start PHP Development Server
        env:
          APP_ENV: 'prod'
        run: php -S localhost:8000 &

      - name: Tests
        run: |
          cd tests
          python -m unittest discover -v